### ISSUE TITLE
Split up server and client gRPC bindings for Rust

### ISSUE THREAD

**Issue by alexjpwalker** [vaticle/typedb-protocol#167]
## Problem to Solve

In Rust, we have the ability to split up our gRPC bindings, producing a server package and a client package. This would currently make the client package imported by `typedb_client` roughly 25% smaller, and the server package imported by `typedb` roughly 15% smaller.

## Proposed Solution

One naive way would be to compile two distinct crates (`typedb_protocol_client` and `typedb_protocol_server`.) But that's not great: we should be importing from `typedb_protocol`, not from `typedb_protocol_client`.

A better strategy exists: compile the server and client bindings individually, then pack them both into the same crate - but gate them behind crate **features**, so if the user wants to depend on the client they specify the following in their `Cargo.toml`:
```toml
[dependencies]
typedb_protocol = { version: "1.0.0", features = ["client"] }
```
And if they want the server, they specify `features = ["server"]`.

## Additional Information

At the time of writing, producing a crate with optional features is most likely not supported in `bazel-distribution`.

**Comment by flyingsilverfin** [comment]
We decided to close this because the library size is still roughly the same size, so the benefit is not worth our time to implement.
